run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
output:
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  dupl:
    threshold: 150
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 30
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kionsoftware/kion-cli
  govet:
    enable:
      - shadow
  lll:
    line-length: 120
    tab-width: 1
  misspell:
    locale: US
    ignore-words:
      - cancelled
  sloglint:
    attr-only: true
  unparam:
    check-exported: false
linters:
  disable-all: true
  enable:
    - asciicheck
    # - dupl
    - errcheck
    - bodyclose
    - goconst
    - gocyclo
    - gofmt
    # - goimports
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
issues:
  exclude:
    - "shadow: declaration of .err. shadows declaration"
    - "shadow: declaration of &#34;err&#34; shadows declaration"
  max-same-issues: 0
  exclude-dirs:
    - tools/*
severity:
  default-severity: error
  rules:
    - linters:
        - gofmt
      severity: info
