run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
output:
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/org/project
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
    ignore-words:
      - cancelled
  lll:
    line-length: 120
    tab-width: 1
  unparam:
    check-exported: false
linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - gofmt
    - misspell
    - unparam
    - gosimple # normally implicit
    - bodyclose
issues:
  exclude:
    - "shadow: declaration of .err. shadows declaration"
    - "shadow: declaration of &#34;err&#34; shadows declaration"
  max-same-issues: 0
  exclude-dirs:
    - tools/*
severity:
  default-severity: error
  rules:
    - linters:
        - gofmt
      severity: info
